### PR TITLE
VSCode ReLaunch error, workflow fix

### LINKED ISSUE #1: Waldiez VSCode Extension activation error after resuming previously opened waldiez tabs
## Search terms

eternal loading, stuck on activating

## Expected Behavior

When starting up, VSCode should be able to resume previously opened .waldiez tabs. 

## Actual Behavior

When the user opens VSCode after a .waldiez file was already left open, VSCode attempts to open it automatically (opening all previous open tabs). But the extension doesn't load. The only way it's fixable is closing all waldiez tabs, restarting VSCode and then open the .waldiez file. 
The Waldiez Extension gets stuck on eternal "Activating.." state, likely because it races to open before the Python interpreter. I came to this conclusion by Ctrl+Shift+P > Developer: Show Running Extensions and noticing the order of activations as well as activation times. 
The error doesn't occur when no waldiez file is open, because the Waldiez Extensions starts up activation only after the user opens a .waldiez file for the first time after opening VSCode.

## Steps to reproduce the bug

Leave a waldiez tab open, close VSCode, reopen VSCode on that workspace. It likely won't load.

## Environment

- Versions:
    - Python version: 3.10
    - waldiez extension version: 0.4.5
    
- OS: Windows 11

### PR DESCRIPTION
**Pull request by amaliacontiero**
Fixes #1 

## Description of the Change
Update to relaunching VSCode with an already opened .waldiez file error. 
Now Waldiez extension waits for python extension and interpreter to be ready before launching the editor. Flow runner is working too.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [x] tests added
- [ ] `CHANGELOG.md` updated (if necessary)

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -24,23 +24,26 @@ export const activate = async (context: ExtensionContext): Promise<void> => {
...
 async function initializeAfterPythonReady(
-    //context: ExtensionContext,
-    provider: WaldiezEditorProvider,
+    context: ExtensionContext,
+    //provider: WaldiezEditorProvider,
     outputChannel: vscode.OutputChannel,
 ) {
     try {
         const pythonExt = vscode.extensions.getExtension("ms-python.python");
+        if (!pythonExt?.isActive) {
```
Comment (lazToum) [inline src/extension.ts]: Maybe move this check  after the one below  (e.g. first check if the extension is found and then if it is active)?
```
if (!pythonExt) {
    traceError("Error: Python extension not found.");
    showOutput();
    return;
}
if (!pythonExt.isActive) {
    traceError("Error: Python extension not active!");
    showOutput();
}
```

File: src/extension.ts [hunk 2]
```diff
@@ -61,28 +64,34 @@ async function initializeAfterPythonReady(
         };
         await waitForInterpreterReady();
 
+        // make sure the discovery/refresh cycle is finished
+        const api = pythonExt.exports.environments; // kicks off a scan *and* waits for it to finish
```
Comment (lazToum) [inline src/extension.ts:68]: Nice!

**Review by lazToum — COMMENTED** [review]
Seems good. Maybe one change with the order of the checks.

File: src/extension.ts (hunk 1 above)
Comment (amaliacontiero) [reply src/extension.ts]: Updated
