### PR TITLE
Waldiez Extension Activation Error Fix

### LINKED ISSUE #1: Waldiez VSCode Extension activation error after resuming previously opened waldiez tabs
## Search terms

eternal loading, stuck on activating

## Expected Behavior

When starting up, VSCode should be able to resume previously opened .waldiez tabs. 

## Actual Behavior

When the user opens VSCode after a .waldiez file was already left open, VSCode attempts to open it automatically (opening all previous open tabs). But the extension doesn't load. The only way it's fixable is closing all waldiez tabs, restarting VSCode and then open the .waldiez file. 
The Waldiez Extension gets stuck on eternal "Activating.." state, likely because it races to open before the Python interpreter. I came to this conclusion by Ctrl+Shift+P > Developer: Show Running Extensions and noticing the order of activations as well as activation times. 
The error doesn't occur when no waldiez file is open, because the Waldiez Extensions starts up activation only after the user opens a .waldiez file for the first time after opening VSCode.

## Steps to reproduce the bug

Leave a waldiez tab open, close VSCode, reopen VSCode on that workspace. It likely won't load.

## Environment

- Versions:
    - Python version: 3.10
    - waldiez extension version: 0.4.5
    
- OS: Windows 11

### PR DESCRIPTION
**Pull request by amaliacontiero**
Fixes #1 

## Description of the Change

Attempting to fix Activation error by waiting for python interpreter to be ready. 
2 main file fixes:

- ./src/extension.ts
- ./src/host/provider.ts

This is a proposed fix, I don't recommend a merge.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [x] tests added
- [ ] `CHANGELOG.md` updated (if necessary)

### CODE REVIEW

**Comment by amaliacontiero** [comment]
It works for me and fixes the activation problem, but I'm not sure if it creates any conflicting issue. 
In addition, I get these at Output:

```
2025-04-28 12:13:04.821 [error] No valid python interpreter found
2025-04-28 12:13:04.821 [error] No valid python interpreter found
2025-04-28 12:13:04.821 [error] Failed to find a valid Python interpreter (>=3.10, <3.13)
2025-04-28 12:13:04.821 [info] Failed to find a valid Python interpreter (>=3.10, <3.13)
``` 

3.13 warning might need fixing [if newer version supports Python 3.13](https://github.com/waldiez/waldiez/issues/101)

File: src/extension.ts [hunk 1]
```diff
@@ -24,30 +24,74 @@ export const activate = async (context: ExtensionContext): Promise<void> => {
...
+                }
+                await new Promise(res => setTimeout(res, 250)); // wait 250ms and try again
+            }
+        };
+        await waitForIntepreterReady();
+
+        // Ensure a valid Python interpreter (>=3.10, <3.13) is available
+        const wrapper = await PythonWrapper.create(waldiezExtensionDisposables);
+        if (!wrapper || !wrapper.executable) {
+            traceError("Failed to find a valid Python interpreter (>=3.10, <3.13)");
```
Comment (lazToum) [inline src/extension.ts:67]: Yep, let's change it to <=3.13

File: src/extension.ts [hunk 2]
```diff
@@ -24,30 +24,74 @@ export const activate = async (context: ExtensionContext): Promise<void> => {
...
+            // showOutput();
+            //vscode.window.showErrorMessage("Failed to find a valid Python interpreter (>=3.10, <3.13)");
+
+            outputChannel.appendLine("Failed to find a valid Python interpreter (>=3.10, <3.13)");
```
Comment (lazToum) [inline src/extension.ts:71]: Same (let's use <= 3.13

**Comment by amaliacontiero** [comment]
Nevermind! I was deceived. While the extension the the workflow viewer now opens instead of eternal loading, flow runner shows warning, therefore this fix is not complete.

image

@lazToum Careful!

**Review by lazToum — CHANGES_REQUESTED** [review]
Thanks! Let's also change the messages to include python 3.13 before merging. It might not completely fix the error, but it's a good start. I'll try to reproduce the error too and see how to continue.

File: src/extension.ts (hunk 1 above)
Comment (lazToum) [reply src/extension.ts:67]: Never mind, it's not related to the issue.

File: src/extension.ts (hunk 2 above)
Comment (lazToum) [reply src/extension.ts:71]: same as above

**Review by lazToum — APPROVED** [review]
